import { saveAs } from "file-saver";
import { GeneratedArchitecture } from "../aiEngine";

/**
 * Generates a Markdown representation of the project architecture and triggers download.
 */
export const exportToMarkdown = (data: GeneratedArchitecture) => {
    const md = `# ${data.title}

> ${data.description}

---

## 🛠 Technology Stack

### Frontend
${data.techStack.frontend.map(item => `- ${item}`).join("\n")}

### Backend
${data.techStack.backend.map(item => `- ${item}`).join("\n")}

### Database
${data.techStack.database.map(item => `- ${item}`).join("\n")}

---

## 📐 System Architecture

### Components & Flow
${data.architecture.map(item => `- ${item}`).join("\n")}

## 🗄 Database Design
${data.database.map(item => `- ${item}`).join("\n")}

---

## ✨ Key Features
${data.features.map(item => `- ${item}`).join("\n")}

---

*Generated by AI Project Architect*
`;

    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
    saveAs(blob, `${data.title.toLowerCase().replace(/\s+/g, "-")}-architecture.md`);
};
